"""Contains all keywords for the keyword extraction process."""

keywords = [
    "Zahnarzt Frankfurt",
    "Zahnärzte Frankfurt",
    "Zahnarztpraxis Frankfurt",
    "Zahnarzt in meiner Nähe",
    "Zahnklinik Frankfurt",
    "Zahnärztliche Praxis Frankfurt",
    "Implantologe Frankfurt",
    "Zahnimplantate Frankfurt",
    "Kieferorthopäde Frankfurt",
    "Kinderzahnarzt Frankfurt",
    "Notfallzahnarzt Frankfurt",
    "Ästhetische Zahnmedizin Frankfurt",
    "Endodontie Frankfurt (Wurzelbehandlung)",
    "Parodontologe Frankfurt (Parodontitis-Spezialist)",
    "Oralchirurg Frankfurt",
    "Prophylaxe Frankfurt (professionelle Zahnreinigung)",
    "Zahnarzt Frankfurt Innenstadt",
    "Zahnarzt Frankfurt Sachsenhausen",
    "Zahnarzt Frankfurt Bockenheim",
    "Zahnarzt Frankfurt Nordend",
    "Zahnarzt Frankfurt Westend",
    "Zahnarzt Frankfurt Bornheim",
    "Zahnarzt Frankfurt Höchst",
    "Angstpatient Zahnarzt Frankfurt",
    "Schmerzfreier Zahnarzt Frankfurt",
    "Zahnarzt mit Ratenzahlung Frankfurt",
    "Günstiger Zahnarzt Frankfurt",
    "Hochwertiger Zahnersatz Frankfurt",
    "Veneers Frankfurt",
    "Bleaching Frankfurt",
    "Unsichtbare Zahnspange Frankfurt",
    "Invisalign Frankfurt",
]
